module.exports = {
  CREATE_QUOTE_REQUEST: 'CREATE_QUOTE_REQUEST',
  CREATE_QUOTE_SUCCESS: 'CREATE_QUOTE_SUCCESS',
  CREATE_QUOTE_FAILURE: 'CREATE_QUOTE_FAILURE',
  FETCH_USER_REQUEST: 'FETCH_USER_REQUEST',
  FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
  FETCH_USER_FAILURE: 'FETCH_USER_FAILURE',
};
